import { ArrowUpRight } from "@phosphor-icons/react";
import type { ReactNode } from "react";
import { Button } from "@/components/ui/button.tsx";
import { Separator } from "@/components/ui/separator.tsx";
import { LOGO_ALT, LOGO_PUBLIC_PATH } from "./brand.ts";
import { handleInternalClick } from "./navigate.ts";
import { ROUTES } from "./routes.ts";

const MAINNET = { network: "Starknet Mainnet · SN_MAIN", router: "0x6048ed36607367ea5ae050c745d47006214ecf66fdbf173d01eba96ec5d780a", target: "0x74637f577350898c64835c88216df3030050828c723c6987a3d97d6d4eb986b", pool: "0x040337b1af3c663e86e333bab5a4b28da8d4652a15a69beee2b677776ffe812a", token: "0x04718f5a0fc34cc1af16a1cdee98ffb20c31f5cd61d6ab07201858f4287c938d" } as const;
const SEPOLIA = { network: "Starknet Sepolia · SN_SEPOLIA", router: "0x0356db61e1d7eaa0417312307c128017e6cc1a85a5a8a649d5c23fee17312b2b", target: "0x0499995a27e1c1ad2d53ecf81649e99f8421e50383f144816809058496034c66", pool: "0x0254a6b2997ef52e9f830ce1f543f6b29768295e8d17e2267d672c552cfe0d91" } as const;
const MAINNET_PROOFS = [["Alice · first Router execution", "0x3e1acf0c893cb5697d48295d629e86fdddd1f8ff1fd1d307c7f2ecab8c7616f"], ["Alice · returned capability", "0x290d3683e674714a79676be0fc13819fc410e0b7e3abb2551529e28a52f83e0"], ["Bob · after private succession", "0xd4be56bfd8b0402e150ced5ee7f8b9c912722f9e4e940d1cc1eda7ee2098d3"]] as const;
const REPOSITORY_URL = "https://github.com/CryptoZephyr/VOCAP";

function DocSection({ id, index, title, children }: { id: string; index: string; title: string; children: ReactNode }) {
  return <section id={id} className="scroll-mt-24 border-t border-border py-12 md:py-16"><p className="mb-3 font-mono text-xs uppercase tracking-[0.16em] text-primary">{index}</p><h2 className="m-0 text-2xl font-semibold tracking-tight md:text-3xl">{title}</h2><div className="mt-5 max-w-[72ch] text-sm leading-relaxed text-muted-foreground">{children}</div></section>;
}

function CodeBlock({ children }: { children: string }) {
  return <pre className="m-0 overflow-x-auto whitespace-pre-wrap break-words text-[0.78rem] leading-relaxed text-muted-foreground"><code>{children}</code></pre>;
}

function Address({ label, value, network = "mainnet" }: { label: string; value: string; network?: "mainnet" | "sepolia" }) {
  const explorer = network === "mainnet" ? "https://starkscan.co/contract/" : "https://sepolia.starkscan.co/contract/";
  return <div className="min-w-0 border border-border p-4"><p className="m-0 text-xs uppercase tracking-[0.12em] text-muted-foreground">{label}</p><code className="mt-3 block break-all font-mono text-xs text-foreground">{value}</code><a className="mt-3 inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline" href={`${explorer}${value}`} target="_blank" rel="noreferrer">Open on Starkscan <ArrowUpRight size={13} /></a></div>;
}

function FlowRow({ number, title, body }: { number: string; title: string; body: string }) {
  return <div className="grid gap-3 border-b border-border py-5 last:border-0 sm:grid-cols-[4rem_1fr]"><span className="font-mono text-xs text-primary">{number}</span><div><h3 className="m-0 text-base font-semibold text-foreground">{title}</h3><p className="m-0 mt-2">{body}</p></div></div>;
}

const QUICKSTART = [
  "npm install vocap-client@0.1.0 starknet@10.5.0",
  "",
  "import { createVocapClient } from \"vocap-client\";",
  "",
  "const vocap = createVocapClient(deployment);",
  "const { transactionHash } = await vocap.submitPrivateResult(walletAccount, sdkResult);",
].join("\\n");

export function DocsPage() {
  return <main className="min-h-[100dvh] bg-background text-foreground">
    <header className="sticky top-0 z-20 flex h-16 items-center justify-between border-b border-border bg-background/95 px-4 backdrop-blur md:px-10"><a href={ROUTES.home} onClick={(event) => handleInternalClick(event, ROUTES.home)} aria-label="VOCAP home"><img className="size-16 object-contain mix-blend-multiply" src={LOGO_PUBLIC_PATH} alt={LOGO_ALT} width={64} height={64} /></a><div className="flex items-center gap-4"><a className="hidden text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground hover:text-foreground md:inline" href="#quickstart">Quickstart</a><a className="hidden text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground hover:text-foreground md:inline" href="#protocol">Protocol</a><a className="hidden text-xs font-semibold uppercase tracking-[0.12em] text-muted-foreground hover:text-foreground md:inline" href="#reference">Reference</a><Button variant="link" nativeButton={false} render={<a href={ROUTES.playground} onClick={(event) => handleInternalClick(event, ROUTES.playground)} />}>Open Playground</Button></div></header>
    <div className="mx-auto grid max-w-6xl gap-12 px-4 py-12 md:grid-cols-[15rem_minmax(0,1fr)] md:px-10 md:py-20">
      <aside className="hidden md:block"><div className="sticky top-24 border-t border-border pt-4"><p className="m-0 font-mono text-xs uppercase tracking-[0.16em] text-primary">Official VOCAP docs</p><nav className="mt-5 grid gap-3 text-sm" aria-label="Documentation navigation"><a href="#getting-started" className="text-muted-foreground hover:text-foreground">Getting started</a><a href="#quickstart" className="text-muted-foreground hover:text-foreground">Quickstart</a><a href="#protocol" className="text-muted-foreground hover:text-foreground">Protocol</a><a href="#integrate" className="text-muted-foreground hover:text-foreground">Integrate</a><a href="#reference" className="text-muted-foreground hover:text-foreground">Reference</a><a href="#api" className="text-muted-foreground hover:text-foreground">Backend API</a><a href="#security" className="text-muted-foreground hover:text-foreground">Security</a><a href="#faq" className="text-muted-foreground hover:text-foreground">FAQ</a></nav></div></aside>
      <article className="min-w-0">
        <div className="mb-14 max-w-3xl"><p className="mb-4 font-mono text-xs uppercase tracking-[0.18em] text-primary">Official VOCAP documentation</p><h1 className="m-0 text-balance text-4xl font-semibold tracking-tight md:text-6xl">Private programmable capability infrastructure for Starknet.</h1><p className="mt-6 max-w-[65ch] text-base leading-relaxed text-muted-foreground">Your asset is your permission. VOCAP binds a real STRK20 asset to one configured Starknet action, then returns that same value to a fresh private note.</p><p className="mt-4 text-sm text-muted-foreground">VOCAP is open source under the MIT License. <a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline" href={REPOSITORY_URL} target="_blank" rel="noreferrer">View the repository <ArrowUpRight size={13} /></a></p><div className="mt-8 flex flex-wrap gap-3"><Button nativeButton={false} render={<a href={ROUTES.playground} onClick={(event) => handleInternalClick(event, ROUTES.playground)} />}>Try a Capability</Button><a className="inline-flex items-center px-3 py-2 text-sm font-semibold text-primary hover:underline" href="#quickstart">Client quickstart</a></div></div>
        <DocSection id="getting-started" index="01 · Getting started" title="What VOCAP does"><p className="m-0">VOCAP is a narrow authorization boundary. The private holder supplies the configured asset through the STRK20 pool. The pool calls <code className="font-mono text-foreground">VocapRouter.privacy_invoke</code>. The Router checks the policy, calls the approved target, and requires the same capability amount to remain available for a fresh private return note.</p><div className="mt-7 grid gap-px border border-border bg-border sm:grid-cols-2"><div className="bg-background p-4"><p className="m-0 font-mono text-xs uppercase text-primary">The asset</p><p className="m-0 mt-2">A private STRK20 note carries the capability.</p></div><div className="bg-background p-4"><p className="m-0 font-mono text-xs uppercase text-primary">The policy</p><p className="m-0 mt-2">Token, amount, target, selector, enabled state, and RETURN mode.</p></div><div className="bg-background p-4"><p className="m-0 font-mono text-xs uppercase text-primary">The action</p><p className="m-0 mt-2"><code className="font-mono text-foreground">premium_action()</code>, with empty target calldata in V1.</p></div><div className="bg-background p-4"><p className="m-0 font-mono text-xs uppercase text-primary">The result</p><p className="m-0 mt-2">A public receipt and a fresh private note, not a public holder record.</p></div></div></DocSection>
        <DocSection id="quickstart" index="02 · Client quickstart" title="Add VOCAP to your app"><p className="m-0">Install the client, create it with your verified deployment settings, then pass it the result from the pinned RC2 privacy SDK. The connected wallet shows the final transaction for approval.</p><div className="mt-6 border border-border bg-muted/40 p-5"><CodeBlock>{QUICKSTART}</CodeBlock></div><p className="mt-5"><code className="font-mono text-foreground">deployment</code> contains the network, Router, pool, policy, token, amount, target, selector, empty target calldata, and optional backend URL. <code className="font-mono text-foreground">sdkResult</code> is the <code className="font-mono text-foreground">callAndProof</code> result from <code className="font-mono text-foreground">PRIVACY-0.14.3-RC.2</code>.</p><p className="mt-5">Viewing keys, note witnesses, and proof material stay with the privacy SDK in the browser. The VOCAP client never asks for them.</p></DocSection>
        <DocSection id="protocol" index="03 · Protocol" title="The RETURN lifecycle"><div className="border-y border-border"><FlowRow number="01" title="Capability" body="The client discovers a private note for the configured token and amount." /><FlowRow number="02" title="Supply" body="The SDK withdraws that exact amount to the Router and prepares one fresh open return note." /><FlowRow number="03" title="Execute" body="The STRK20 pool calls the Router. Pool caller, policy, token, amount, target, selector, mode, and note are checked before the target call." /><FlowRow number="04" title="Return" body="The approved target runs. Balance conservation and the Router approval return the same amount to the pool for a fresh private note." /></div><div className="mt-7 border border-primary p-5"><p className="m-0 font-medium text-foreground">The core invariant</p><p className="m-0 mt-2">No required asset, no authorized action. V1 supports RETURN only. It doesn’t support consume mode, arbitrary predicates, hidden target execution, or generic ownership proofs.</p></div></DocSection>
        <DocSection id="integrate" index="04 · Integrate" title="What the client handles"><p className="m-0">The client keeps the integration boundary small. It:</p><ul className="m-0 mt-5 grid gap-3 pl-5"><li>checks that the privacy SDK result calls the configured pool through <code className="font-mono text-foreground">apply_actions</code>,</li><li>submits that call through the connected wallet,</li><li>builds the reviewed V1 Router callback when your app owns the privacy SDK builder, and</li><li>reads policies, executions, and transaction status from the public projection API.</li></ul><p className="mt-5">The wallet remains the write boundary. V1 target calldata stays empty, and the chain receipt remains authoritative for transaction success.</p></DocSection>
        <DocSection id="reference" index="05 · Reference" title="Contracts, deployments, and evidence"><p className="m-0">These values are the repository’s current deployment record. Mainnet is evidence-only in the Playground. Sepolia is the lower-risk environment for a future wallet-funded run.</p><h3 className="m-0 mt-8 text-base font-semibold text-foreground">Mainnet</h3><p className="m-0 mt-2 font-mono text-xs text-muted-foreground">{MAINNET.network} · policy 1 · 1 STRK · {MAINNET_PROOFS.length} recorded executions</p><div className="mt-4 grid gap-3 sm:grid-cols-2"><Address label="VocapRouter" value={MAINNET.router} /><Address label="Approved target" value={MAINNET.target} /><Address label="STRK20 pool" value={MAINNET.pool} /><Address label="STRK token" value={MAINNET.token} /></div><div className="mt-8 border-y border-border">{MAINNET_PROOFS.map(([label, hash]) => <div className="grid gap-3 border-b border-border py-4 last:border-0 sm:grid-cols-[1fr_2fr_auto] sm:items-center" key={hash}><span className="text-sm font-semibold text-foreground">{label}</span><code className="break-all font-mono text-xs text-muted-foreground">{hash}</code><a className="inline-flex items-center gap-1 text-xs font-semibold text-primary hover:underline" href={`https://starkscan.co/tx/${hash}`} target="_blank" rel="noreferrer">Receipt <ArrowUpRight size={13} /></a></div>)}</div><h3 className="m-0 mt-10 text-base font-semibold text-foreground">Sepolia</h3><p className="m-0 mt-2 font-mono text-xs text-muted-foreground">{SEPOLIA.network} · policy 1 · 1 STRK · 2 STRK pool fee</p><div className="mt-4 grid gap-3 sm:grid-cols-3"><Address label="VocapRouter" value={SEPOLIA.router} network="sepolia" /><Address label="Approved target" value={SEPOLIA.target} network="sepolia" /><Address label="STRK20 pool" value={SEPOLIA.pool} network="sepolia" /></div></DocSection>
        <DocSection id="api" index="06 · Backend integration" title="Read public projections"><p className="m-0">The backend indexes finalized public receipts into PostgreSQL. It exposes scoped reads and transaction registration. Execution listings omit private note identifiers.</p><div className="mt-6 overflow-x-auto border border-border"><table className="w-full min-w-[38rem] border-collapse text-left text-sm"><thead><tr className="border-b border-border text-xs uppercase tracking-[0.12em] text-muted-foreground"><th className="px-4 py-3 font-medium">Method</th><th className="px-4 py-3 font-medium">Route</th><th className="px-4 py-3 font-medium">Purpose</th></tr></thead><tbody>{[["GET", "/api/v1/policies?network=sepolia&routerAddress=0x…&policyId=1", "Read one policy projection"], ["GET", "/api/v1/executions?network=sepolia&routerAddress=0x…", "List finalized public executions"], ["GET", "/api/v1/transactions?network=sepolia&routerAddress=0x…&txHash=0x…", "Read registered lifecycle state"], ["POST", "/api/v1/transactions", "Register a router_execution hash"]].map(([method, route, purpose]) => <tr className="border-b border-border last:border-0" key={route}><td className="px-4 py-4 font-mono text-xs text-primary">{method}</td><td className="px-4 py-4 font-mono text-xs text-foreground">{route}</td><td className="px-4 py-4 text-muted-foreground">{purpose}</td></tr>)}</tbody></table></div><div className="mt-6 border border-border bg-muted/40 p-5"><CodeBlock>{`POST /api/v1/transactions\ncontent-type: application/json\n\n{\n  "network": "sepolia",\n  "routerAddress": "0x…",\n  "txHash": "0x…",\n  "kind": "router_execution"\n}`}</CodeBlock></div><p className="mt-5">The registration route is scope-checked against the backend deployment and accepts only a Router execution. The chain receipt remains authoritative if the projection is delayed or unavailable.</p></DocSection>
        <DocSection id="security" index="07 · Security" title="Trust assumptions and limits"><div className="grid gap-0 border-y border-border"><FlowRow number="Private" title="Kept in the wallet" body="Viewing key, note witnesses, private registry, proof-signing material, and private holder state." /><FlowRow number="Public" title="Visible at the boundary" body="Pool calls, transaction timing, Router policy checks, target state changes, and finalized event data." /><FlowRow number="Trust" title="What VOCAP assumes" body="The user controls the wallet and viewing key. The selected privacy services, RPC, pool, and target are the intended deployments." /></div><ul className="m-0 mt-7 grid gap-3 pl-5"><li>Never send a private key, viewing key, note witness, registry, or proof material to the backend.</li><li>Never treat a wallet-submitted hash as success. Wait for an accepted receipt and matching <code className="font-mono text-foreground">PolicyExecuted</code> event.</li><li>Never infer private note ownership from a public event.</li><li>Never mix Mainnet and historical Sepolia deployment values.</li><li>Future Mainnet writes require a fresh wallet, allowance, pool fee, service, and chain-state check.</li></ul><Separator className="my-7" /><p className="m-0">The active client is pinned to <code className="font-mono text-foreground">PRIVACY-0.14.3-RC.2</code> at commit <code className="font-mono text-foreground">9bfeb8dd35565a2915a0617dff3f649bd5bb891a</code>. Service image digests remain unavailable, so that provenance limitation stays explicit.</p></DocSection>
        <DocSection id="faq" index="08 · FAQ" title="Common integration questions"><div className="grid gap-0 border-t border-border">{[["What exactly is private?", "The current capability holder and private holder-to-holder transfer can remain private through STRK20. The target action and public chain metadata remain observable."], ["Can the same capability be reused?", "Yes. After successful RETURN execution, the browser SDK must rediscover the fresh private note before using it again."], ["What happens when a capability is transferred?", "The sender's private note is spent and the recipient receives a new valid private note. Recipient-side discovery confirms the private succession."], ["Does VOCAP hide target calldata?", "No. The V1 target call uses premium_action() with empty calldata, and the public execution boundary remains observable."], ["Can any contract integrate VOCAP?", "A reviewed integration can protect selected functions by explicitly trusting the Router and defining a matching policy. Arbitrary unreviewed targets are outside the V1 surface."], ["Is Mainnet ready for another write?", "The recorded Mainnet lifecycle is evidence. A new write still requires fresh fee, allowance, service, wallet, and chain-state checks."], ["Where do I exercise it?", "Use the Capability Playground. It keeps Mainnet read-only and makes Sepolia the explicit write environment when a real wallet and private note are available."]].map(([question, answer]) => <details key={question} className="border-b border-border py-5"><summary className="cursor-pointer list-none pr-8 text-base font-semibold text-foreground">{question}</summary><p className="m-0 mt-3 max-w-[58ch] text-sm leading-relaxed text-muted-foreground">{answer}</p></details>)}</div></DocSection>
        <div className="border-t border-border pt-8 text-sm text-muted-foreground"><a className="inline-flex items-center gap-1 font-semibold text-primary hover:underline" href={ROUTES.home} onClick={(event) => handleInternalClick(event, ROUTES.home)}>Back to VOCAP <ArrowUpRight size={14} /></a></div>
      </article>
    </div>
  </main>;
}
